---
title: Project Review Template 
author: AIDAN TROHA
date: "`r file.mtime(knitr::current_input())`"
format: 
  html:
    toc: true
    toc-depth: 3
    number-sections: true
---

# Overview

Title of project:

Name of project author(s): Chris Okitondo & Irene Cavros

Name of project reviewer: Aidan troha


# Instructions

Write your comments and feedback below for each section/component of the project. The goal should be to help the author improve their project. Make comments as constructive and actionable as possible. You can provide both criticism and praise.

For each component, pick one summary statement by deleting the ones that do not apply and keeping only the one that you think most closely summarizes a given component. 

Make sure your final document compiles/knits into a readable, well-formatted html document.

Delete any sections/text of this template that are not part of your final review document. (Including these instructions.)


# Specific project content evaluation
Evaluate the different parts of the project by filling in the sections below.


## Background, Context and Motivation
How well is the context of the project described? Is a comprehensive background, including summary of previous/related work given? Is the project well placed into the context of existing work (including proper referencing of existing work). Is it clear why the project was undertaken and what new information it hopes to provide?

### Feedback and Comments

Your references show the application of the results you obtain, the need for inquiry, and motivation for analyses. Overall, this is a really good introduction section that just needs a little polishing o=to improve flow.

### Summary assessment (PICK ONE, DELETE THE OTHERS)
* strong contextualization and motivation


## Question description
How well and clear are the question(s)/hypotheses the project aims to address described? Is it clear how the questions relate to the data?


### Feedback and Comments

You could spend some time further developing the aims of your study. You have a well defined main goal regarding risk factors for flu contraction, but you might want to look further into other confounders.

### Summary assessment
* question/hypotheses somewhat explained


## Data description
How well is the data overall described? Is the source provided? Is a codebook or other meta-information available that makes it clear what the data is? 

### Feedback and Comments

The documentation for what each variable represents is clear enough that the meaning of each variable is understandable. The README.md files could be expanded to include more details about factor variables.

### Summary assessment
* source and overall structure of data well explained


## Data wrangling and exploratory analysis
How well is the data cleaned/processed and explored? Are all steps reasonable and well explained? Are alternatives discussed and considered? Are meaningful exploratory results shown (e.g. in the supplementary materials)?

### Feedback and Comments

I see no issue with the methods you employ fro data manipulation. All steps seem appropriate.

### Summary assessment
* essentially no weaknesses in wrangling and exploratory component



## Appropriateness of Analysis
Were the analysis methods appropriate for the data? Was the analysis done properly? Were different components of the analysis (e.g. performance measure, variable selection, data pre-processing, model evaluation) done in the best way possible and explained well?

### Feedback and Comments

ROC curves are the easiest method of logistic regression model quality analysis we learned, and I think it is employed well here. In future, the model could potentially be optimized to improve the ROC output, time permitting.

### Summary assessment
* strong and reasonable analysis

## Presentation
How well are results presented? Are tables and figures easy to read and understand? Are the main figures/tables publication level quality? 

### Feedback and Comments

There may be just a few too many elements to the large table found in the Results section. It takes up a lot of space, but it is important to show any relationships that may exist between the variables. Other figures seem appropriately sized and integral to your results.

### Summary assessment
* results are presented ok, with room for improvement


## Discussion/Conclusions
Are the study findings properly discussed? Are strengths and limitations acknowledged? Are findings interpreted properly?

### Feedback and Comments

All elements are discussed in appropriate detail. 

### Summary assessment
* strong, complete and clear discussion


## Further comments

Great job guys! Great work you have put forth throughout this semester!



# Overall project content evaluation
Evaluate overall features of the project by filling in the sections below.


## Structure
Is the project well structured? Are files in well labeled folders? Do files have reasonable names? Are all "junk" files not needed for analysis/reproduction removed? By just looking at files and folders, can you get an idea of how things fit together?

### Feedback and Comments

Using the default structure of the fold isn't very user-friendly. Personally, I like to be able to find all the component parts of each section of the results in order as described by the manuscript.

### Summary assessment
* mostly clear, but some confusing parts (e.g. useless files, things in the wrong folders)


## Documentation 
How well is the project documented? Are you able to understand each step of the whole analysis, each decision that was made, and each line of code? Is enough information provided as comments in code or as part of Rmd files? 

### Feedback and Comments

More or less, I can follow the jist of your analyses.  

### Summary assessment
* fully and well documented



## Reproducibility
Are all results fully reproducible? Is documentation provided which clearly explains how to reproduce things, and does it work without the need for any manual intervention? Are you able to re-run the whole analysis without having to do manual interventions/edits?

### Feedback and Comments

WRITE YOUR FEEDBACK HERE

Do to the fact that you have to navigate to several different documents located in different places, it makes it difficult, but not impossible, to reproduce the entire project.

### Summary assessment

* fully reproducible without issues


## Thoroughness
How thorough was the overall study? Were alternatives (e.g. different ways of processing the data or different models) considered? Were alternatives discussed? Were the questions/hypotheses fully and thoroughly addressed?

### Feedback and Comments

I can tell you put a lot of work into this project, so good job guys!

### Summary assessment
* strong level of thorougness


## Further comments

_Add any other comments regarding the overall project here. Write anything you think can help your classmate improve their project._




